---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: argocd
  namespace: argocd
spec:
  interval: 15m
  chart:
    spec:
      chart: argo-cd
      version: 4.5.8
      sourceRef:
        kind: HelmRepository
        name: argocd
        namespace: flux-system
      interval: 15m
  values:
    server:
      ingress:
        enabled: true
        ingressClassName: nginx
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
          hajimari.io/appName: ArgoCD
          hajimari.io/icon: robot
        hosts:
          - "argocd.${SECRET_DOMAIN}"
        tls:
          - secretName: argocd-tls-certificate
            hosts:
              - "argocd.${SECRET_DOMAIN}"
      metrics: &metrics
        enabled: true
    dex:
      enabled: false
    controller:
      metrics: *metrics
    repoServer:
      metrics: *metrics
    redis:
      metrics: *metrics
