---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: argocd
  namespace: argocd
spec:
  interval: 15m
  chart:
    spec:
      chart: argo-cd
      version: 4.5.8
      sourceRef:
        kind: HelmRepository
        name: argocd
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  valuesFrom:
    - kind: ConfigMap
      name: argocd-values
      valuesKey: values.yaml
      optional: false
