---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - helm-release.yaml
configMapGenerator:
- name: argocd-values
  namespace: argocd
  files:
  - values.yaml
