# yamllint disable-file
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    nginx.ingress.kubernetes.io/proxy-body-size: 10G
    nginx.ingress.kubernetes.io/proxy-request-buffering: "off"
  generation: 2
  labels:
    app: longhorn-ingress
    app.kubernetes.io/instance: longhorn-system
    app.kubernetes.io/name: longhorn
    app.kubernetes.io/version: v1.3.1
    argocd.argoproj.io/instance: longhorn-system
  name: longhorn-ingress
  namespace: longhorn-system
spec:
  ingressClassName: nginx
  rules:
  - host: longhorn.{{ .Values.global.domain }}
    http:
      paths:
      - backend:
          service:
            name: longhorn-frontend
            port:
              number: 80
        path: /
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - longhorn.{{ .Values.global.domain }}
    secretName: longhorn-cert-tls
