---
creation_rules:
  - path_regex: provision/.*\.sops\.ya?ml
    unencrypted_regex: "^(kind)$"
    key_groups:
      - age:
          - age1exydp42j29asc8l7dnvm2a3kme42nvvzqa76499jhgl4a3dh6dzqjp522h
  - path_regex: cluster/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - age1exydp42j29asc8l7dnvm2a3kme42nvvzqa76499jhgl4a3dh6dzqjp522h
