# yamllint disable-file
{{- if .Values.ombi.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.ombi.project }}
  namespace: {{ .Values.ombi.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: {{ .Values.syncWave }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.project }}
  destination:
    name: in-cluster
    namespace: {{ .Values.namespace }}
  source:
    chart: {{ .Values.ombi.Chart }}
    repoURL: {{ .Values.ombi.repoURL }}
    targetRevision: {{ .Values.ombi.targetRevision }}
    helm:
      releaseName: {{ .Values.ombi.releeaseName }}
      values:
        image:
          repository: ghcr.io/linuxserver/ombi
          tag: 4.22.5
        env:
          TZ: America/Chicago
          PUID: "1000"
          PGID: "1000"
        # envFrom:
          # - configMapRef:
              # name: proxy-config
        # controller:
          # annotations:
            # configmap.reloader.stakater.com/reload: "proxy-config"
        ingress:
          main:
            enabled: true
            ingressClassName: nginx
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt-production
              kubernetes.io/tls-acme: "true"
            hosts:
              - host: &host ombi.{{ $.Values.global.domain }}
                paths:
                  - path: /
                    pathType: Prefix
            tls:
              - hosts:
                  - *host
        podSecurityContext:
          fsGroup: 1000
          fsGroupChangePolicy: OnRootMismatch
        persistence:
          config:
            enabled: true
            type: pvc
            accessMode: ReadWriteOnce
          storageClass: longhorn
          size: 1Gi
      resources:
        requests:
          cpu: 50m
          memory: 384Mi
        limits:
          cpu: 1000m
          memory: 512Mi
{{- end }}
