speedtest-exporter:
  image:
    repository: ghcr.io/miguelndecarvalho/speedtest-exporter
    tag: v3.5.2
  metrics:
    enabled: true
    serviceMonitor:
      interval: 5m
      scrapeTimeout: 1m
    prometheusRule:
      enabled: false
      downloadLimit: 200
      uploadLimit: 25
      pingLimit: 30
      jitterLimit: 35
