---
longhorn:
  defaultSettings:
    defaultReplicaCount: 2
    nodeDownPodDeletionPolicy: delete-both-statefulset-and-deployment-pod
    replicaAutoBalance: best-effort
    concurrentAutomaticEngineUpgradePerNodeLimit: 1
    # backupTarget: s3://longhorn@minio/
    # backupTargetCredentialSecret: longhorn-backup
  persistence:
    defaultClass: true
    defaultClassReplicaCount: 2
    reclaimPolicy: Retain
