# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: kube-system
stringData:
    api-key: ENC[AES256_GCM,data:TKEfg8a8opPK15smIDxWlJT33WJ+elIDpbhkVHXD1M5d+kIv4Q==,iv:0T8pWZ2GOZmnncsiDXxIdKYK5gKkCt0PBoupj8NcJu0=,tag:fDKJAskbP4IYYfUJfbIuIw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1exydp42j29asc8l7dnvm2a3kme42nvvzqa76499jhgl4a3dh6dzqjp522h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4WFdTMHkxcUttQlRvYTF1
            ZUhPNnRDQy9ORVBmOWE4NkJ3NUJHVFhLK0ZBClRSM0lKZERmZko4VGUvVUhYRGNk
            ci9Dc0VwR2xvSVluT25zTnNIS3NuQzgKLS0tIHh6bXc2ckZNNXNac0MwKzJhV3lw
            Q2k0Q0w1Y0xmZmw5YXlidnVJUEVhaEEKMJ9Oz6R7h3Q0Y4WWtkxy04hlg/g1cRkk
            14m9F/JUMoC42RJ8ym5sTgp4t7pLOBDy5mQ2+TUxCLbxLAUhSRiU4Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-23T15:07:39Z"
    mac: ENC[AES256_GCM,data:kYaMl6kZS2aLrAbxYyOQTx4vdz0S1cxqWhS1JAQ07o0IiKDB1fi8U2w7gztNqI7uRYujKFL7S2KuAae2ht/z1vWaU56oRt/JZ/E2L2BEeC3WS6PPyRgtoiyrDkv2g6Nt7hDUky31nYK5JCnzdJ9JlttRpC8/yV90ZrJHgYNZc0M=,iv:8RG1WSCZW/C1/spsoQaESkkIL+Wt08YqsVsOmZZZKSA=,tag:r31E1ShxvIQQpTgCO0apUA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
