# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: external-dns-cloud-credentials
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:AT1FdzfZBJT0H2+1IYSdjqCN/h+O7qst8ec3,iv:CL24pNMs0defuc79TYWuHJXsDT4IgtnmpBhKYarEzPI=,tag:F1IuR5OB60I73LjBoIiPjA==,type:str]
    api-key: ENC[AES256_GCM,data:EIBE2zS5Ax/bx3meDxmSm1a8vsJJPfjct+qxuAW8v9r7Bk6q7Q==,iv:eZ5pRKF+dvkb/yHN+cWH8v6ZTfC5B9A2oyXVwf4/Rpk=,tag:RMSy8PFmZfep+oZbVmy+bA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1exydp42j29asc8l7dnvm2a3kme42nvvzqa76499jhgl4a3dh6dzqjp522h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCYnl4d3p0dHpCZi9nYmU1
            SEloc3RLUXk0d0ltOGRSTFhESWFRaVU3QkFjCjBUWFVsa2haZXpGc2FtcjF2V0My
            cWxqTXF0T2dabVFxTCtZOEozSmlhdDAKLS0tIGNkNzkzS1BscWdGTVRIMTFtcU1k
            SFpkQnBzbE5KdHBUUjUwR1lzOXlSdUEKX139RNIX9uSFi18FZzJ/CR1IxhVX7ZRl
            YuGBT2D2NURskGkQ2itfOHRH548CFAErVbKXXRVvnd4AC/Eq04bEkg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-23T15:07:39Z"
    mac: ENC[AES256_GCM,data:gURF7VFVhwISsKJkSTBzvFj7Qn3kyS4YBGFRWukBf95Nhjqwg/vOWElkgomfrqRUEgo33WAOhPxPi97tlQTqMPaNZzJcBruKs+BVbm/9/FS//GOio0QCdJ1b9NvD6fMiHK0++CmYxKWBRPMenAcRybr1LGbUB4LyYUQT11g02HE=,iv:h/+jSv4YJhNaoFZs8EyYXFiF+rMpfYRl5J2stjR0Njs=,tag:n54uLrBOmPNK45Vs/xkm6Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
