---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: America/Chicago
  METALLB_LB_RANGE: 192.168.1.240-192.168.1.250
  METALLB_K8S_GATEWAY_ADDR: 192.168.1.240
  METALLB_INGRESS_ADDR: 192.168.1.241
