apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: trow
  namespace: trow
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: platform
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
  destination:
    name: in-cluster
    namespace: trow
  source:
    plugin:
      name: gen-plugin
      env:
        - name: SECRET_DOMAIN
          value: $SECRET_DOMAIN
    chart: trow
    repoURL: https://trow.io
    targetRevision: 0.3.5
    helm:
      releaseName: trow
      valueFiles:
        - values-prod.yaml
      values: |
        trow:
          domain: registry.{{ .Values.domain }}
          validation:
            enabled: false
            allowDocker: false
            allowKubernetes: true
            allowPrefixes: []
            allowImages: []
            disallowLocalPrefixes: []
            disallowLocalImages: []
            proxyDockerHub: false
        ingress:
          enabled: true  # TODO https://github.com/ContainerSolutions/trow/issues/282
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt-production
            nginx.ingress.kubernetes.io/proxy-body-size: '0'
          hosts:
            - host: &host registry.{{ .Values.domain }}
              paths:
                - /
          tls:
            - secretName: trow-tls-certificate
              hosts:
                - *host
        volumeClaim:
          storageClassName: longhorn
