longhorn:
  defaultSettings:
    defaultReplicaCount: 2
    nodeDownPodDeletionPolicy: delete-both-statefulset-and-deployment-pod
    replicaAutoBalance: best-effort
    concurrentAutomaticEngineUpgradePerNodeLimit: 1
    # backupTarget: s3://longhorn@minio/
    # backupTargetCredentialSecret: longhorn-backup
  persistence:
    defaultClass: true
    defaultClassReplicaCount: 2
    reclaimPolicy: Retain
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      nginx.ingress.kubernetes.io/proxy-body-size: "10G"
      nginx.ingress.kubernetes.io/proxy-request-buffering: "off"
      kubernetes.io/ingress.class: "nginx"
      cert-manager.io/cluster-issuer: letsencrypt-production
      cert-manager.io/common-name: longhorn.$SECRET_DOMAIN
        # nginx.ingress.kubernetes.io/auth-url: "http://oauth2-proxy.kube-system.svc.cluster.local:80/oauth2/auth"
        # nginx.ingress.kubernetes.io/auth-signin: https://auth.rsr.net/oauth2/start
    hosts: longhorn.$SECRET_DOMAIN
    tls: true
    tls-secret: longhorn-cert-tls
