# yamllint disable-file
{{- if .Values.platform.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: platform
  syncPolicy:
    # automated:
      # selfHeal: true
      # prune: true
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    - group: argoproj.io
      kind: Application
      jsonPointers:
        - /spec/syncPolicy/automated
  destination:
    name: in-cluster
    namespace: platform
  source:
    path: 'cluster/apps/argocd/apps/system'
    repoURL: {{ .Values.repoURL }}
    targetRevision: "{{ .Values.platform.targetRevision }}"
    helm:
      valueFiles:
      - values-{{ .Values.env }}.yaml
      values: |
        argocd:
          targetRevision: {{ .Values.platform.targetRevision }}

        domain: {{ .Values.domain }}
        repoURL: {{ .Values.repoURL }}
        env: {{ .Values.env }}
{{- end }}
