# yamllint disable-file
{{- range $index, $stack := .Values.stacks }}
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: {{ $stack.name }}
  namespace: {{ $.Release.Namespace }}
spec:
  generators:
    - git:
        repoURL: {{ $.Values.repo.url }}
        revision: {{ $.Values.repo.revision }}
        directories:
          - path: "{{ $stack.path }}/*"
  template:
    metadata:
      name: '{{ `{{path.basename}}` }}'
      # annotations:
        # argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
        # argocd.argoproj.io/manifest-generate-paths: '{{ `{{path}}` }}'
    spec:
      destination:
        name: in-cluster
        namespace: '{{ default `{{path.basename}}` $stack.namespace }}'
      project: default
      source:
        repoURL: {{ $.Values.repo.url }}
        path: '{{ `{{path}}` }}'
        targetRevision: {{ $.Values.repo.revision }}
      syncPolicy:
        automated:
          prune: {{ $stack.prune }}
          selfHeal: {{ $stack.selfHeal }}
        retry:
          limit: 3
          backoff:
            duration: 1m
            factor: 2
            maxDuration: 16m
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true
{{- end }}
