loki-stack:
  loki:
    fullnameOverride: loki
    # isDefault: false
    # config:
      # existingSecret: loki
    # ingress:
      # enabled: true
      # ingressClassName: nginx
      # annotations:
        # cert-manager.io/cluster-issuer: letsencrypt-production
      # hosts:
        # - host: &host loki.{{ $.Values.global.domain }}
          # paths:
            # - /
      # tls:
        # - hosts:
            # - *host
          # secretName: loki-cert-tls
    persistence:
      enabled: true
      storageClassName: longhorn
      size: 10Gi
    serviceMonitor:
      enabled: true
  promtail:
    fullnameOverride: promtail
    config:
      lokiAddress: http://loki:3100/loki/api/v1/push
    serviceMonitor:
      enabled: true
