lidarr:
  image:
    repository: ghcr.io/k8s-at-home/lidarr-nightly
    tag: v1.1.1.2664
  env:
    TZ: America/Chicago
  ingress:
    main:
      enabled: true
      ingressClassName: nginx
      annotations:
        kubernetes.io/tls-acme: "true"
      hosts:
        - host: &host lidarr.{{ $.Values.global.domain }}
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - *host
  podSecurityContext:
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000
    fsGroupChangePolicy: OnRootMismatch
  persistence:
    config:
      enabled: true
      type: pvc
      accessMode: ReadWriteOnce
      storageClass: longhorn
      size: 1Gi
    nfs-downloads:
      enabled: true
      existingClaim: nfs-downloads-pvc
      mountPath: /downloads
  resources:
    requests:
      cpu: 10m
      memory: 200Mi
    limits:
      cpu: 100m
      memory: 256Mi
