apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: '{{ `{{path.basename}}` }}'
  namespace: {{ .Release.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "5"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: platform
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
  destination:
    name: in-cluster
    namespace: {{ .Release.namespace }}
  source:
    plugin:
      name: argocd-vault-plugin
      # envFrom:
        # - secretRef:
            # name: cluster-secrets
    chart: trow
    repoURL: https://trow.io
    targetRevision: 0.3.5
    helm:
      releaseName: trow
      values: |
        trow:
          domain: "registry."{{ .Values.domain }}
          validation:
            enabled: false
            allowDocker: false
            allowKubernetes: true
            allowPrefixes: []
            allowImages: []
            disallowLocalPrefixes: []
            disallowLocalImages: []
            proxyDockerHub: false
