jellyfin:
  ingress:
    main:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-production
        hajimari.io/appName: Jellyfin
        hajimari.io/icon: filmstrip
      hosts:
        - host: &host jellyfin.{{ $.Values.global.domain }}
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: jellyfin-cert-tls
          hosts:
            - *host
