apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/tls-acme: 'true'
  labels:
    app.kubernetes.io/instance: portainer
    app.kubernetes.io/name: portainer
  name: portainer
  namespace: {{ .Release.namespace }}
spec:
  ingressClassName: nginx
  rules:
    - host: portainer.{{ $.Values.global.domain }}
      http:
        paths:
          - backend:
              service:
                name: portainer
                port:
                  number: 9000
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - portainer.{{ $.Values.global.domain }}
      secretName: portainer-cert-tls
