---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: homelab
spec:
  serviceAccountName: tekton-admin
  pipelineRef:
    name: homelab
  workspaces:
    - name: shared-data
      volumeClaimTemplate:
        spec:
          storageClassName: longhorn
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
