apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: root
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    - group: argoproj.io
      kind: Application
      jsonPointers:
        - /spec/syncPolicy/automated
  destination:
    name: in-cluster
    namespace: argocd
  source:
    path: 'cluster/argocd/apps/root'
    repoURL: https://github.com/jjalvare/thishouse.git
    targetRevision: main
    helm:
      valueFiles:
        - values.yaml
      values: |
        argocd:
          targetRevision: main
