---
# repoURL: https://github.com/jjalvare/thishouse
# env: "prod"
namespace: argocd
domain: ""
global:
  repoURL: https://github.com/jjalvare/thishouse
  env: "prod"
  domain: ""
spec:
  destination:
    server: https://kubernetes.default.svc
repo:
  url: https://github.com/jjalvare/thishouse.git
  revision: main
system:
  enabled: true
  revision: main
platform:
  enabled: true
  revision: main
applications:
  - name: apps
    enabled: true
    targetRevision: main
    path: "cluster/argocd/applications"
    selfHeal: true
    prune: true
    project: apps
    namespace: apps
applicationSet:
  - name: system
    enabled: true
    targetRevision: main
    path: "cluster/argocd/system"
    selfHeal: true
    prune: true
  - name: platform
    path: "cluster/argocd/platform"
    selfHeal: true
    prune: true
    enabled: true
    targetRevision: main
