spec:
  destination:
    server: https://kubernetes.default.svc
repo:
  url: https://github.com/jjalvare/thishouse.git
  revision: main
stacks:
  - name: system
    path: "cluster/apps/argocd/apps/system"
  - name: platform
    path: "cluster/apps/argocd/apps/platform"
