---
repoURL: https://github.com/jjalvare/thishouse
env: "prod"
namespace: argocd
domain: ""
global:
  domain: ""
spec:
  destination:
    server: https://kubernetes.default.svc
repo:
  url: https://github.com/jjalvare/thishouse.git
  revision: main
system:
  enabled: true
  revision: main
platform:
  enabled: true
  revision: main
stacks:
  - name: system
    enabled: true
    targetRevision: main
    path: "cluster/apps/argocd/apps/system"
    selfHeal: false
    prune: false
  - name: platform
    path: "cluster/apps/argocd/apps/platform"
    selfHeal: false
    prune: false
    enabled: true
    targetRevision: main
