apiVersion: v1
appVersion: "1.0"
description: Applications
name: Apps
version: 0.0.0
dependencies:
  - name: home-assistant
    version: 13.4.2
    repository: https://k8s-at-home.com/charts/
  - name: ombi
    version: 11.5.2
    repository: https://k8s-at-home.com/charts/
  - name: lidarr
    version: 14.2.2
    repository: https://k8s-at-home.com/charts/
  - name: bazarr
    version: 10.6.2
    repository: https://k8s-at-home.com/charts/
  - name: jellyfin
    version: 9.3.0
    repository: https://k8s-at-home.com/charts/
  - name: prowlarr
    version: 4.5.2
    repository: https://k8s-at-home.com/charts/
  - name: radarr
    version: 16.3.2
    repository: https://k8s-at-home.com/charts/
  - name: sonarr
    version: 16.3.2
    repository: https://k8s-at-home.com/charts/
